name: pymodal-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pyansys
    - pytest
    - pytest-cov
    - docutils
    - doc8
    - flake8